#!/usr/bin/env python3

# list all file in directory ./examples/ 
# and write to file ./examples.js

import os

examples = []
for fname in sorted(os.listdir('./examples/')):
    # read the file
    # the file is organized in the form :
    # // Comment line 1
    # // Comment line ...
    # ////
    # <Code>
    with open('./examples/' + fname, 'r') as f:
        content = f.read()
        comments, code = content.split('////')
        comments = [c.lstrip('//').strip() for c in comments.split('\n') if c != '']
        examples.append([fname.split('-')[1], comments, code.lstrip('\n')])
        
# write to file
with open('./examples.js', 'w') as f:
    f.write('/* This file is generated by examples_to_jsfile.py */\n')
    f.write('/* Do not edit this file */\n')
    f.write('/* Edit the files in ./examples/ instead */\n')
    f.write('/* The format of the file is as follows:\n')
    f.write('/* // Comment line 1\n')
    f.write('/* // Comment line ...\n')
    f.write('/* ////\n')
    f.write('/* <Code>\n')
    f.write('*/\n')
    f.write('\n')
    f.write('export let examples = [];\n')
    for fname, comments, code in examples:
        f.write(f'examples.push({{name : {repr(fname)}, comments : {repr(comments)}, code : {repr(code)}}});\n')
    # f.write('export examples;\n')

